# Generated by Django 4.2.3 on 2023-08-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertable',
            name='logi_user_company',
            field=models.CharField(default='Doshi', max_length=45),
        ),
        migrations.AddField(
            model_name='customertable',
            name='logi_user_diasplayname',
            field=models.CharField(default='displayname', max_length=45),
        ),
        migrations.AddField(
            model_name='customertable',
            name='logi_user_user',
            field=models.CharField(default='userId', max_length=45),
        ),
    ]
